# 1) Create a new service principal in the Azure portal for your app:
# az ad sp create-for-rbac --name "myApp" --role contributor \
#   --scopes /subscriptions/{subscription-id}/resourceGroups/{resource-group} \
#   --sdk-auth
# {
#    "clientId": "<GUID>",
#    "clientSecret": "<GUID>",
#    "subscriptionId": "<GUID>",
#    "tenantId": "<GUID>",
#    (...)
#}

# 2) Select Security > Secrets and variables > Actions.
# Paste the entire JSON output from the Azure CLI command above into the secret's value field.
# Give the secret the name AZURE_CREDENTIALS

on:
  workflow_call:

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  service_principal_secret_check:
    runs-on: ubuntu-latest
    outputs:
      is_AZURE_CREDENTIALS_set: ${{ steps.checksecret.outputs.is_AZURE_CREDENTIALS_set }}
    steps:
      - name: Check secret set
        id: checksecret
        run: |
          set -x
          echo "is_AZURE_CREDENTIALS_set=${{ env.AZURE_CREDENTIALS != '' }}" >> $GITHUB_OUTPUT

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        inlineScript: |
          az account show
